apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: demo-pv
